BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TagType" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"TypeName"	TEXT NOT NULL UNIQUE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "MediaTable" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Location"	TEXT NOT NULL UNIQUE,
	"Rating"	REAL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "GroupTable" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "GroupedOrderedMedia" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"GroupId"	INTEGER NOT NULL,
	"MediaId"	INTEGER NOT NULL,
	"Order"	INTEGER NOT NULL,
	FOREIGN KEY("GroupId") REFERENCES "GroupTable"("Id") ON DELETE CASCADE,
	FOREIGN KEY("MediaId") REFERENCES "MediaTable"("Id") ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "RatingTable" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Score"	REAL NOT NULL,
	"ImageId"	INTEGER NOT NULL UNIQUE,
	FOREIGN KEY("ImageId") REFERENCES "MediaTable"("Id") ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TagAlias" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Alias"	TEXT NOT NULL UNIQUE,
	"TagId"	INTEGER NOT NULL,
	FOREIGN KEY("TagId") REFERENCES "TagTable"("Id") ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TagTable" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Tag"	TEXT NOT NULL UNIQUE,
	"TagTypeId"	INTEGER NOT NULL,
	FOREIGN KEY("TagTypeId") REFERENCES "TagType"("Id") ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "TagToImage" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"TagId"	INTEGER NOT NULL,
	"MediaId"	INTEGER NOT NULL,
	FOREIGN KEY("MediaId") REFERENCES "MediaTable"("Id") ON DELETE CASCADE,
	FOREIGN KEY("TagId") REFERENCES "TagTable"("Id") ON DELETE CASCADE,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
